services:
  webapp:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_DB: meudb
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
